### ISSUE TITLE
Documentation on use

### ISSUE THREAD

**Issue by MMathisLab** [ETHZ-INS/DLCAnalyzer#1]
Dear @lukasvonziegler thanks for this great package, which we link to DLC-Utils (https://github.com/DeepLabCut/DLCutils)! 

I would like to request that you add a clear readme with usage tips.

- i.e. if an individual has the outputs of deeplabcut (.h5/.csv files) how can they load and use this code base in R? 

- perhaps supply a Jupyter Notebook with demo code for [how to load](https://github.com/DeepLabCut/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb) and [use R](https://www.datacamp.com/community/blog/jupyter-notebook-r?utm_source=adwords_ppc&utm_campaignid=1565261270&utm_adgroupid=67750485268&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=332661264365&utm_targetid=dsa-473406574235&utm_loc_interest_ms=&utm_loc_physical_ms=1018145&gclid=EAIaIQobChMI-9-w0emL6AIViMDICh3HmwBUEAAYASAAEgId9vD_BwE)?

**Comment by lukasvonziegler** [comment]
Thank you for the interest in the code. I agree, it is in a very crude version at the moment. I will be working on a proper documentation and release it as soon as possible.
This will include clear demo code and information about compatible file formats and library versions for any used packages.

Best,
Lukas

**Comment by MMathisLab** [comment]
you may at least want to link to your preprint ASAP ;)

**Comment by lukasvonziegler** [comment]
As requested, there is now a documentation that outlines the best use of the code. It is in form of a markdown document (README.md) that can be viewed directly on github  or downloaded as html file. Also, the pre-print is linked in the README
