### ISSUE TITLE
Issues with CleanTracking Data

### ISSUE THREAD

**Issue by afbrokaw** [ETHZ-INS/DLCAnalyzer#19]
Hello @lukasvonziegler and others!

I'm running into a funny problem and I'm not sure what's going on. Somewhere between importing a csv file and trying to use CleanData, some of my columns gets randomly converted to NAs. When I try to run CleanTrackingData, I get the error:  imputeTS: No imputation performed for column 3 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
I'm not sure why this is happening, as the original files do have values in those columns. 

It's also not always the same columns that lose data - for example, when trying to import a file, I would lose data in columns "odorspot" and "controlspot". However, after restarting my script and rerunning the same commands, I instead lost data from "tl" and "controlspot", having made no changes to the csv file. 

Any thoughts on what might be going on here? It is making it impossible for me to batch the files, since some of them fail at the data cleaning point due to this error.

**Comment by afbrokaw** [comment]
(Hopefully) reproducible example: 
m318_nov16_t1 <- ReadDLCDataFromCSV(file = "318_t1_11162022.csv", fps = 50)
PlotPointData(m318_nov16_t1, points = c("odorspot","nose","tailbase")) #all columns seem to plot as you would expect, indicating there are values in all columns
m318_nov16_t1_clean <- CleanTrackingData(m318_nov16_t1, likelihoodcutoff = 0.95)

[1] "interpolating points with likelihood < 0.95"
Warning messages:
1: imputeTS: No imputation performed for column 2 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
2: imputeTS: No imputation performed for column 3 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
3: imputeTS: No imputation performed for column 2 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
4: imputeTS: No imputation performed for column 3 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
5: imputeTS: No imputation performed for column 2 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation
 
6: imputeTS: No imputation performed for column 3 because of this Error in na_interpolation(data[, i], option, maxgap): Input data needs at least 2 non-NA data point for applying na_interpolation

I've tried playing around with the likelihood cutoff, but it doesn't seem to make a difference. These particular columns indicate a static spot, so should not be experiencing much moving/jumping around. 

Curiously, a different set of tracks but with all the same columns runs just fine. 
m318_nov18_t1 <- ReadDLCDataFromCSV(file = "318_t1_11182022.csv", fps = 50)
m318_nov18_t1_clean <- CleanTrackingData(m318_nov18_t1, likelihoodcutoff = 0.9) #no error messages

See attached for example files. 
[318_t1_1116202
[318_t1_11182022.csv](https://github.com/ETHZ-INS/DLCAnalyzer/files/10449171/318_t1_11182022.csv)
2.csv](https://github.com/ETHZ-INS/DLCAnalyzer/files/10449170/318_t1_11162022.csv)

**Comment by lukasvonziegler** [comment]
Hi there afbrokaw,

I had a quick look at one of your file and quickly plotted a histogram of the likelihood values of individual points. 
you can do this by using: 

hist(m318_nov16_t1$data$tr$likelihood)

or whatever point you want to check. i noticed that the points "tr" "br" and "controlspot" have low likelihood values (~0.8, ~0.4 and ~0.4).

So when you use the function to clean the tracking data with a cutoff of 0.95 you remove this points completely and get NA values. There are a few solutions:

-Retrain the DLC network to increase the likelihood for these points (work intensive). overall your network seems to still make quite a few mistakes/low confidence tracking and could be improved.

- Lower the likelihood cutoff to 0.3 or just don't clean up the data at all. this may be a problem if your points on the mouse are misplaced quite often and you really need to clean up the data. when looking at the raw data prior to cleanup (using PlotPointData(m318_nov18_t1 )) i see many misplacements that you have to deal with and 0.3 seems to be to low of a cutoff to get rid of them.

- if are only interested in the median value of your zone points to generate the areas later (tr, br, controlspot etc) simply ignore the warning and never use these points on a per frame level. you can find the median value of them in the m318_nov16_t1$median.data whenever you need them and they are not altered or removed during the clean up. You can also still use these to define zones and so on.

I hope this helps you,
Lukas

**Comment by afbrokaw** [comment]
Thanks for the response! That makes sense and I'll try those suggestions. At the moment, I'm mostly in the phase of figuring out potential analysis pipelines, so for future data would probably do more training pre-analysis. It's useful to know that the static values can be used later without the frame level.

**Comment by afbrokaw** [comment]
Sorry, related-ish question. Is it possible to manually set zone areas without having to have the tracked data? For example, in addition to the total arena, I would like to be able to manually add an inner square that would separate tracks that in the center of the arena from the edges. How would you go about doing that? 

Thanks!

**Comment by lukasvonziegler** [comment]
Yes!
The easiest way would be to add our OFT Zones. they will add a periphery, and center zone as well as corner zones and work with any arena that is basically a square box.

Use: 
Tracking <- AddOFTZones(Tracking, scale_center = 0.5,scale_periphery  = 0.8 ,scale_corners = 0.4, points = c("tl","tr","br","bl"))

you can modulate scale_center and scale_periphery  to your preference. to check the zones use visually use:

PlotZones(Tracking)

how to add custom zones from other points median.data is also described in the Readme under "OFT analysis of a single file"

if you want to specify the coordinates completely on your own you can always brute force a zone in by defining

Tracking$zones$my.zone <- data.frame(x = c(100,1000,1000,100),  y = c(100,100,1000,1000))

or you can use it as a scaled version from another zone by i.e using 

Tracking$zones$my.zone2 <- ScalePolygon(Tracking$zones$my.zone, factor = 2)

this would add my.zone2 which is my.zone1 scaled by a factor of 2

**Comment by afbrokaw** [comment]
Great, thank you for clarifying! Appreciate this code and your help! :)
